### ISSUE TITLE
Issue with yarn install 'no manifest.json'

### ISSUE THREAD

**Issue by mishingo** [robbinfellow/sage-laravel-mix#1]
## Submit a feature request or bug report

- [ x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x ] This is a feature request
- [ x] This is a bug report
- [ x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

Had an issue where the yarn install saying it couldnt find the manifest.json so i created an empty dist folder with a blank manifest.json and it worked

**Comment by mishingo** [comment]
glad you started this btw the sage official webpack sucks compared to laravel-mix

**Comment by robbinfellow** [comment]
Hi @mishingo!

Sorry about the issue with the dist folder, it should be [resolved](https://github.com/robbinfellow/sage-laravel-mix/commit/4691331c02e6ef0fe056da7792c14d6a367431e9) now.

I'm glad you enjoy it, laravel-mix is awesome indeed 👍
